### ISSUE TITLE
RFC-0025: Implement tiptap editor in Pecha tool HTR for highlighting error by reviewer/final reviewer (2)

### ISSUE THREAD

**Issue by tentamdin** [OpenPecha/pecha-tool-for-line-image#22]
### Description
Pecha tool HRT team wants a feature where a reviewer or a final reviewer can highlight the error in the transcript before rejecting it to the transcriber. That way transcriber will know their mistake and correct it.

### Completion Criteria
The reviewer or final reviewer can highlight the error and reject the task. The transcriber will get the rejected task with a highlighted transcript.

### Implementation Plan
Install the Tiptap package and its required extensions. Configure the requirement so the user can highlight the errors before rejecting the task. Save the highlighted errors with the transcript in the database. 

### Sub Task

- [x] install titptap package
- [x] change input/textarea to tiptap editor
- [x] save transcript in db with editor based on roles (rejected or submit)

**Comment by tentamdin** [comment]
![Image](https://github.com/OpenPecha/pecha-tool-for-line-image/assets/38410384/15c35d7d-33a7-4919-8980-56def68ba356)


Problem: all the transcripts are coming as single lines for the final reviewer and also can't be redone and undo.
I have fixed the above with tiptap extensions.
